<#
.SYNOPSIS
  Equalizer APO wiring for the DDJ-200 bridge. Only needed if the bridge shows
  a RED tray icon (it cannot write to APO's config folder). Run as
  Administrator in that case.

  The bridge normally does this itself: if Peace (or you) made the config
  folder user-writable, it creates ddj200.txt and adds the Include line on
  start-up without any help.

  - creates <APO config dir>\ddj200.txt (flat)
  - grants your user account write access to that one file
  - adds "Include: ddj200.txt" to config.txt (backed up first)

.PARAMETER Remove
  Undo everything above.

.PARAMETER User
  Account that will run the bridge. Defaults to the account running this
  script; override if UAC prompted you for a different admin account.
#>
param(
    [string]$ApoConfigDir = "C:\Program Files\EqualizerAPO\config",
    [string]$IncludeFile  = "ddj200.txt",
    [string]$User         = "$env:USERDOMAIN\$env:USERNAME",
    [switch]$Remove
)

$ErrorActionPreference = "Stop"
trap [System.UnauthorizedAccessException] {
    Write-Host "Access denied - re-run this script from an Administrator PowerShell." -ForegroundColor Yellow
    exit 1
}
$configTxt   = Join-Path $ApoConfigDir "config.txt"
$includePath = Join-Path $ApoConfigDir $IncludeFile
$includeLine = "Include: $IncludeFile"

if (-not (Test-Path $configTxt)) {
    Write-Error "Equalizer APO not found at '$ApoConfigDir'. Install it first: https://sourceforge.net/projects/equalizerapo/"
}

$lines = Get-Content $configTxt
$hasInclude = ($lines | Where-Object { $_.Trim() -ieq $includeLine }).Count -gt 0

if ($Remove) {
    if ($hasInclude) {
        Copy-Item $configTxt "$configTxt.bak" -Force
        $lines | Where-Object { $_.Trim() -ine $includeLine } | Set-Content $configTxt -Encoding utf8
        Write-Host "Removed '$includeLine' from config.txt"
    }
    if (Test-Path $includePath) {
        Remove-Item $includePath -Force -Confirm:$false
        Write-Host "Deleted $includePath"
    }
    Write-Host "Done."
    exit 0
}

if (-not (Test-Path $includePath)) {
    "# Generated by DDJ200Bridge - flat" | Set-Content $includePath -Encoding utf8
    Write-Host "Created $includePath"
}

# Let the (non-admin) bridge process rewrite this one file.
icacls "$includePath" /grant "${User}:(M)" | Out-Null
Write-Host "Granted Modify on $IncludeFile to $User"

if (-not $hasInclude) {
    Copy-Item $configTxt "$configTxt.bak" -Force
    Add-Content $configTxt "`r`n$includeLine" -Encoding utf8
    Write-Host "Added '$includeLine' to config.txt (backup: config.txt.bak)"
} else {
    Write-Host "config.txt already includes $IncludeFile"
}

Write-Host ""
Write-Host "APO wiring complete. Reminder: Equalizer APO must be enabled on each output"
Write-Host "device you use (Start > Equalizer APO > Configurator), then reboot once."
